#!/usr/local/bin/ansible-playbook
---
- name: Deploy a Kubernetes cluster
  hosts: localhost
  connection: local
  vars:
    kubernetes_version: 1.25.6
    containerd_version: 1.6.19
    runc_version: 1.1.4
    cni_plugins_version: 1.2.0
    
    # cluster networking
    pod_network_cidr: 10.10.0.0/16
    service_network_cidr: 10.255.0.0/16

  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  roles:
    - role: sysprep
      tags:
        - sysprep

    - role: kubernetes
      tags:
        - kubernetes
