---
- name: Get Helm install script
  get_url: 
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh

- name: Execute the install script
  command: bash /tmp/get_helm.sh
