---
- name: Send over kubeadm config file
  template:
    src: kubeadm-init.yaml
    dest: /etc/kubernetes/kubeadm-init.yaml

- name: Initialize Kubernetes
  command: "kubeadm init --config /etc/kubernetes/kubeadm-init.yaml"
  args:
    creates: /etc/kubernetes/admin.conf

- name: Wait for port 6443 to be ready
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 6443
    delay: 30

- name: Send over Calico custom resources file
  template:
    src: calico.yaml
    dest: /etc/kubernetes/calico.yaml

- name: Apply the Calico custom resources
  command: kubectl apply -f /etc/kubernetes/calico.yaml
