---
#
# Install CNI plugins
#
- name: Make folder for cni-plugins binaries
  file:
    state: directory
    path: /opt/cni/bin

- name: Unarchive cni-plugins tarball
  unarchive:
    src: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-amd64-v{{ cni_plugins_version }}.tgz"
    dest: /opt/cni/bin
    remote_src: yes 
