---
- name: Install kubeadm, kubelet, kubectl binaries
  apt:
    name: '{{ item }}={{ kubernetes_version }}-00'
    update_cache: True
    allow_downgrades: True
  loop:
    - kubeadm
    - kubelet
    - kubectl

- name: Hold the installed kubeadm, kubelet, kubectl packages to prevent upgrades
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  loop:
    - kubeadm
    - kubelet
    - kubectl

- name: Setup kubectl completion for root
  lineinfile:
    line: 'source <(kubectl completion bash)'
    path: /root/.bashrc
    state: present

- name: Setup bash completion for root
  lineinfile:
    line: 'source /usr/share/bash-completion/bash_completion'
    path: /root/.bashrc
    state: present

- name: Setup the environment variable for kubeconfig
  lineinfile:
    line: '{{ line }}'
    path: /root/.bashrc
    state: present
  loop:
    - 'export KUBECONFIG=/etc/kubernetes/admin.conf'
    - 'alias k=kubectl'
  loop_control:
    loop_var: line

- name: Pull the kubeadm images
  command: kubeadm config images pull
