---
#
# Install runc
# 
- name: Make tempfile for runc download
  tempfile:
  register: runc_download

- name: Download runc
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64
    checksum: "sha256:https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.sha256sum"
    dest: '{{ runc_download.path }}'

- name: Install runc
  copy:
    src: '{{ runc_download.path }}'
    dest: /usr/local/sbin/runc
    mode: 0755
    remote_src: yes
